const swaggerAutogen = require('swagger-autogen')();
const config = require('config');
const host = config.get('host');
const { port = 5000, apiRootPrefix, apiVerPrefix } = config.get('apiConfig');

const outputFile = './swagger.json';
const endpointsFiles = ['./server'];

const doc = {
  definitions: {
    User: {
      name: 'John Doe',
      email: 'john.doe@somemail.com',
      password: 'jd123456&',
    },
    UserResp: {
      _id: '6108588085fe156111731ad0',
      name: 'John Doe',
      email: 'john.doe@somemail.com',
      date: '2021-08-02T20:41:36.516Z',
      __v: 0,
    },
    TokenResp: {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjEwODU4ODA4NWZlMTU2MTExNzMxYWQwIn0sImlhdCI6MTYyODQzNjc2NCwiZXhwIjoxNjI4NDQwMzY0fQ.ss_4I4RspagVF_DBbb0S9eY96qX-R6ZUrdFaDOZDetM"
    },
    ContactId: '611b7bc3919737614941a07d',
    Contact: {
      "name": "Sarah Smith",
      "email": "sarah.smith@somemail.com",
      "phone": "555 - 5555 - 5555",
      "type": "professional"
    },
    ContactResp: {
      "type": "professional",
      "_id": "611b7bc3919737614941a07d",
      "userId": "6108588085fe156111731ad0",
      "name": "Sarah Smith",
      "email": "sarah.smith@somemail.com",
      "phone": "555 - 5555 - 5555",
      "date": "2021-08-17T09:05:07.732Z",
      "__v": 0
    },
    ContactsResp: [
      '{contact1}',
      '{contact2}',
      '{contact...}'
    ],
    LogIn: {
      email: 'john.doe@somemail.com',
      password: 'jd123456&',
    },
    Message: {
      msg: 'Detailed message goes here',
    },
    ValidationErrors: {
      errors: [
        {
          value: 'caused field value',
          msg: 'Detailed message goes here',
          param: 'caused field name',
          location: 'caused field location (body/header/etc)',
        },
      ],
    },
  },
  securityDefinitions: {
    bearerJwtAuth: {
      type: 'apiKey',
      in: 'header',
      name: 'authorization',
      scheme: 'bearer',
      bearerFormat: 'JWT',
      description:
        'Bearer schema based JWT authorization according to rfc7519. e.g.: "Bearer {token}"',
    },
  },
  info: {
    version: '1.0.0',
    title: 'Contact-keeper API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: `${host}:${port}`,
  basePath: `${apiRootPrefix}${apiVerPrefix}`,
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
};

swaggerAutogen(outputFile, endpointsFiles, doc);
